### ISSUE TITLE
logs table can be slow to query.

### ISSUE THREAD

**Issue by danmarsden** [EduardoKrausME/moodle-auth_bruteforce#2]
The logs table can be quite large and can be quite slow to query - please include a statement in the readme of this file that states that your plugin uses the logs table and with large sites this may slightly impact the login time for users.

**Comment by danmarsden** [comment]
in future - you might think about a way you could use the MUC to store known blocked IP addresses instead of having to query the logs table each time.

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-auth_bruteforce/commit/99ce9aadce556acbe09efae6050ae0be7424a612
