### ISSUE TITLE
please improve plugins db description

### ISSUE THREAD

**Issue by danmarsden** [EduardoKrausME/moodle-auth_bruteforce#3]
In the plugins db you need to add something along the lines of:

Moodle provides built-in support for brute force login checking as documented here:
https://docs.moodle.org/dev/Security:Brute-forcing_login

But - the core feature completely locks the affected users account. This plugin will block access to the IP address attempting to access your site no matter what username is being passed.

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-auth_bruteforce/commit/5c3c2d1cade90df547bd581ec5b08c33231ae964
