### ISSUE TITLE
consider returning an invalid password response instead of die with a custom string.

### ISSUE THREAD

**Issue by danmarsden** [EduardoKrausME/moodle-auth_bruteforce#4]
by returning the custom string die(get_string("auth_bruteforcebloqued", "auth_bruteforce")); you are letting the external party know that they are being blocked. It might be better simply to return a false login so they don't just rotate the IP address and keep trying.

This isn't a blocker for approval - just something for you to think about.

**Comment by eduardokraus** [comment]
I think a student who made a mistake will be confused if he can't log in and the support won't be able to find out if he doesn't inform.
