### ISSUE TITLE
please improve plugins db description.

### ISSUE THREAD

**Issue by danmarsden** [EduardoKrausME/moodle-auth_bruteforce#7]
I think you are still misunderstanding.. but as mentioned in issue #3 and also 3 times in the tracker issue here:
https://tracker.moodle.org/browse/CONTRIB-7587

you need to update the Moodle.org plugins db description to cover more details about what your plugin does.

go here:
https://moodle.org/plugins/auth_bruteforce
click on "developer zone"
click on "edit this plugin" (at the bottom of the page.)

then add a lot more detail about what your plugin does to the "description" field on this page.

copying from my original comment in the moodle tracker.. 
we really need you to improve the plugins db description to describe how your plugin differs from the core brute force functionality in Moodle and what features it provides - I would also like to see your plugin description provide a direct link to:
https://docs.moodle.org/dev/Security:Brute-forcing_login

**Comment by eduardokraus** [comment]
Done

**Comment by danmarsden** [comment]
It doesn't look like you are seeing the updates we are posting in the tracker?
https://tracker.moodle.org/browse/CONTRIB-7587

There is a trademark issue that needs to be resolved before we continue the review.
